/**
 * GitHub Pages host provider.
 *
 * The artist is already GitHub-connected (the `repo` scope), so publishing to Pages
 * needs no second OAuth: enable Pages on the generated repo, then commit a deploy
 * workflow that builds the Astro site and publishes it. The push of that workflow
 * file is what triggers the first (and only) build — see the ordering note below.
 *
 * Docs:
 *   Pages REST:  https://docs.github.com/rest/pages/pages
 *   Astro guide: https://docs.astro.build/en/guides/deploy/github/
 */

import type { GeneratedRepo } from '../github';
import type { DeployState, HostProvider, ProvisionTokens, SiteHandle } from './types';

const GH_API = 'https://api.github.com';
const UA = 'gesso-provision-worker';
const WORKFLOW_FILE = 'gesso-pages.yml';
const WORKFLOW_PATH = `.github/workflows/${WORKFLOW_FILE}`;

function authHeaders(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': UA,
  };
}

/**
 * Enable Pages with the GitHub Actions build type. Idempotent: a 409 means Pages is
 * already enabled (e.g. a retry), which is fine. We enable it *before* committing the
 * workflow so that when the workflow's push triggers the run, the deploy-pages step
 * already has somewhere to publish to.
 */
async function enablePages(token: string, owner: string, repo: string): Promise<void> {
  const res = await fetch(`${GH_API}/repos/${owner}/${repo}/pages`, {
    method: 'POST',
    headers: authHeaders(token),
    body: JSON.stringify({ build_type: 'workflow' }),
  });
  // 201 created, 409 already-enabled — both acceptable. Older repos with Pages set to
  // a legacy branch source return 409 too; flip them to the workflow build type.
  if (res.status === 409) {
    await fetch(`${GH_API}/repos/${owner}/${repo}/pages`, {
      method: 'PUT',
      headers: authHeaders(token),
      body: JSON.stringify({ build_type: 'workflow' }),
    });
    return;
  }
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`enable Pages failed (${res.status}): ${body}`);
  }
}

/**
 * The deploy workflow. Builds the Astro site (URL is the github.io origin; BASE_PATH
 * is the serving subpath — empty for a `<user>.github.io` user site served at the
 * root, `/<repo>` for a project site — consumed by the template's astro.config) and
 * publishes it through the first-party Pages actions. Templated per repo.
 */
function deployWorkflow(owner: string, branch: string, basePath: string): string {
  const origin = `https://${owner.toLowerCase()}.github.io`;
  return `# Generated by Gesso — builds your portfolio and publishes it to GitHub Pages.
name: Deploy to GitHub Pages

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Let a newer publish supersede an in-flight one, but never cancel a run mid-deploy.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
        env:
          URL: ${origin}
          BASE_PATH: "${basePath}"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
`;
}

/** Create (or update, on retry) a file in the repo. */
async function commitFile(
  token: string,
  opts: { owner: string; repo: string; branch: string; path: string; content: string; message: string },
): Promise<void> {
  // Look up an existing sha so a retry updates in place instead of 422-ing.
  const getRes = await fetch(
    `${GH_API}/repos/${opts.owner}/${opts.repo}/contents/${opts.path}?ref=${opts.branch}`,
    { headers: authHeaders(token) },
  );
  let sha: string | undefined;
  if (getRes.ok) sha = ((await getRes.json()) as { sha: string }).sha;

  const putRes = await fetch(`${GH_API}/repos/${opts.owner}/${opts.repo}/contents/${opts.path}`, {
    method: 'PUT',
    headers: authHeaders(token),
    body: JSON.stringify({
      message: opts.message,
      content: encodeBase64(opts.content),
      branch: opts.branch,
      ...(sha ? { sha } : {}),
    }),
  });
  if (!putRes.ok) {
    const body = await putRes.text();
    throw new Error(`commit ${opts.path} failed (${putRes.status}): ${body}`);
  }
}

/**
 * Summarize the latest Pages deploy by reading our deploy workflow's most recent run.
 *
 * NOTE: do NOT use `GET /repos/{owner}/{repo}/pages` `.status` — that field only
 * tracks the *legacy* branch-based builder and stays `null` forever for Actions/
 * workflow-built Pages, so the wizard would hang on "building" even after the site
 * went live. The workflow run is the real signal: its success includes the
 * deploy-pages step, i.e. the site is actually published.
 */
export async function getPagesDeployState(
  token: string,
  owner: string,
  repo: string,
): Promise<DeployState> {
  const res = await fetch(`${GH_API}/repos/${owner}/${repo}/actions/runs?per_page=10`, {
    headers: authHeaders(token),
  });
  if (!res.ok) return 'unknown';
  const data = (await res.json()) as {
    workflow_runs?: Array<{ path: string; status: string; conclusion: string | null }>;
  };
  // Runs come back newest-first; pick the latest run of our deploy workflow.
  const run = (data.workflow_runs ?? []).find((r) => r.path === WORKFLOW_PATH);
  if (!run) return 'unknown'; // workflow hasn't started yet — keep polling
  if (run.status !== 'completed') return 'building'; // queued / in_progress
  if (run.conclusion === 'success') return 'ready';
  if (['failure', 'timed_out', 'startup_failure', 'cancelled'].includes(run.conclusion ?? '')) {
    return 'error';
  }
  return 'unknown';
}

export const githubPagesProvider: HostProvider = {
  id: 'github-pages',
  needsNetlify: false,
  formBackend: 'formsubmit',

  async createSite({ tokens, repo }: { tokens: ProvisionTokens; repo: GeneratedRepo }): Promise<SiteHandle> {
    // A repo named exactly `<owner>.github.io` is a GitHub *user site*: it serves at
    // the root (https://owner.github.io/) with no subpath. Anything else is a project
    // site served under /<repo>, which needs BASE_PATH so the build's links resolve.
    const owner = repo.owner.toLowerCase();
    const isUserSite = repo.name.toLowerCase() === `${owner}.github.io`;
    const basePath = isUserSite ? '' : `/${repo.name}`;
    const siteUrl = `https://${owner}.github.io${basePath}/`;

    // Enable Pages first, then commit the workflow. The admin-config commit already
    // landed (admin stage) with no workflow present, so it couldn't build; this
    // workflow push is the single trigger, and it builds the already-correct HEAD.
    await enablePages(tokens.githubToken, repo.owner, repo.name);
    await commitFile(tokens.githubToken, {
      owner: repo.owner,
      repo: repo.name,
      branch: repo.defaultBranch,
      path: WORKFLOW_PATH,
      content: deployWorkflow(repo.owner, repo.defaultBranch, basePath),
      message: 'ci(gesso): publish to GitHub Pages',
    });
    return {
      siteUrl,
      adminUrl: `${siteUrl}admin/`,
      dashboardSlug: repo.name,
      repoOwner: repo.owner,
      repoName: repo.name,
    };
  },

  async getDeployState({ tokens, site }: { tokens: ProvisionTokens; site: SiteHandle }): Promise<DeployState> {
    if (!site.repoOwner || !site.repoName) return 'unknown';
    return getPagesDeployState(tokens.githubToken, site.repoOwner, site.repoName);
  },
};

function encodeBase64(text: string): string {
  const bytes = new TextEncoder().encode(text);
  let bin = '';
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}
