/**
 * GitHub Pages host provider.
 *
 * The artist is already GitHub-connected (the `repo` scope), so publishing to Pages
 * needs no second OAuth: enable Pages on the generated repo, then commit a deploy
 * workflow that builds the Astro site and publishes it. The push of that workflow
 * file is what triggers the first (and only) build — see the ordering note below.
 *
 * Docs:
 *   Pages REST:  https://docs.github.com/rest/pages/pages
 *   Astro guide: https://docs.astro.build/en/guides/deploy/github/
 */

import type { GeneratedRepo } from '../github';
import type { DeployState, HostProvider, ProvisionTokens, SiteHandle } from './types';

const GH_API = 'https://api.github.com';
const UA = 'easel-provision-worker';
const WORKFLOW_PATH = '.github/workflows/easel-pages.yml';

function authHeaders(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': UA,
  };
}

/**
 * Enable Pages with the GitHub Actions build type. Idempotent: a 409 means Pages is
 * already enabled (e.g. a retry), which is fine. We enable it *before* committing the
 * workflow so that when the workflow's push triggers the run, the deploy-pages step
 * already has somewhere to publish to.
 */
async function enablePages(token: string, owner: string, repo: string): Promise<void> {
  const res = await fetch(`${GH_API}/repos/${owner}/${repo}/pages`, {
    method: 'POST',
    headers: authHeaders(token),
    body: JSON.stringify({ build_type: 'workflow' }),
  });
  // 201 created, 409 already-enabled — both acceptable. Older repos with Pages set to
  // a legacy branch source return 409 too; flip them to the workflow build type.
  if (res.status === 409) {
    await fetch(`${GH_API}/repos/${owner}/${repo}/pages`, {
      method: 'PUT',
      headers: authHeaders(token),
      body: JSON.stringify({ build_type: 'workflow' }),
    });
    return;
  }
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`enable Pages failed (${res.status}): ${body}`);
  }
}

/**
 * The deploy workflow. Builds the Astro site with the subpath baked in (URL is the
 * github.io origin, BASE_PATH is /<repo>, consumed by the template's astro.config)
 * and publishes it through the first-party Pages actions. Templated per repo.
 */
function deployWorkflow(owner: string, repo: string, branch: string): string {
  const origin = `https://${owner.toLowerCase()}.github.io`;
  return `# Generated by Easel — builds your portfolio and publishes it to GitHub Pages.
name: Deploy to GitHub Pages

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Let a newer publish supersede an in-flight one, but never cancel a run mid-deploy.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
        env:
          URL: ${origin}
          BASE_PATH: /${repo}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
`;
}

/** Create (or update, on retry) a file in the repo. */
async function commitFile(
  token: string,
  opts: { owner: string; repo: string; branch: string; path: string; content: string; message: string },
): Promise<void> {
  // Look up an existing sha so a retry updates in place instead of 422-ing.
  const getRes = await fetch(
    `${GH_API}/repos/${opts.owner}/${opts.repo}/contents/${opts.path}?ref=${opts.branch}`,
    { headers: authHeaders(token) },
  );
  let sha: string | undefined;
  if (getRes.ok) sha = ((await getRes.json()) as { sha: string }).sha;

  const putRes = await fetch(`${GH_API}/repos/${opts.owner}/${opts.repo}/contents/${opts.path}`, {
    method: 'PUT',
    headers: authHeaders(token),
    body: JSON.stringify({
      message: opts.message,
      content: encodeBase64(opts.content),
      branch: opts.branch,
      ...(sha ? { sha } : {}),
    }),
  });
  if (!putRes.ok) {
    const body = await putRes.text();
    throw new Error(`commit ${opts.path} failed (${putRes.status}): ${body}`);
  }
}

/**
 * Summarize the latest Pages build. `GET /repos/{owner}/{repo}/pages` carries a
 * top-level `status` that reflects the most recent deployment regardless of build
 * type (workflow or legacy), so it's the one signal that works for our Actions-driven
 * Pages. Null/queued/building ⇒ keep polling; built ⇒ live; errored ⇒ failed.
 */
export async function getPagesDeployState(
  token: string,
  owner: string,
  repo: string,
): Promise<DeployState> {
  const res = await fetch(`${GH_API}/repos/${owner}/${repo}/pages`, {
    headers: authHeaders(token),
  });
  if (!res.ok) return 'unknown';
  const data = (await res.json()) as { status?: string | null };
  switch (data.status) {
    case 'built':
      return 'ready';
    case 'errored':
      return 'error';
    case 'building':
    case 'queued':
      return 'building';
    default:
      return 'unknown'; // null — not deployed yet, keep polling
  }
}

export const githubPagesProvider: HostProvider = {
  id: 'github-pages',
  needsNetlify: false,
  formBackend: 'formsubmit',

  async createSite({ tokens, repo }: { tokens: ProvisionTokens; repo: GeneratedRepo }): Promise<SiteHandle> {
    // Enable Pages first, then commit the workflow. The admin-config commit already
    // landed (admin stage) with no workflow present, so it couldn't build; this
    // workflow push is the single trigger, and it builds the already-correct HEAD.
    await enablePages(tokens.githubToken, repo.owner, repo.name);
    await commitFile(tokens.githubToken, {
      owner: repo.owner,
      repo: repo.name,
      branch: repo.defaultBranch,
      path: WORKFLOW_PATH,
      content: deployWorkflow(repo.owner, repo.name, repo.defaultBranch),
      message: 'ci(easel): publish to GitHub Pages',
    });
    const siteUrl = `https://${repo.owner.toLowerCase()}.github.io/${repo.name}/`;
    return {
      siteUrl,
      adminUrl: `${siteUrl}admin/`,
      dashboardSlug: repo.name,
      repoOwner: repo.owner,
      repoName: repo.name,
    };
  },

  async getDeployState({ tokens, site }: { tokens: ProvisionTokens; site: SiteHandle }): Promise<DeployState> {
    if (!site.repoOwner || !site.repoName) return 'unknown';
    return getPagesDeployState(tokens.githubToken, site.repoOwner, site.repoName);
  },
};

function encodeBase64(text: string): string {
  const bytes = new TextEncoder().encode(text);
  let bin = '';
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}
